language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx
sudo: false

# Run builds for all the supported trains
rust:
  - nightly
  - stable

# OSX with Rust nightly fails because of cargo cache error
# "error: failed to remove: /Users/travis/build/klausi/rustnish/target/debug/rustnish.dSYM"
matrix:
  allow_failures:
    - os: osx
      rust: nightly
