[package]
name = "rustnish"
version = "0.0.1"
authors = [ "Klaus Purer <klaus.purer@gmail.com>" ]

[dependencies]
hyper = ">=0.11.13"
futures = ">=0.1.14"
tokio-core = ">=0.1.8"
error-chain = ">=0.11.0"
tk-listen = ">=0.1.1"
