[package]
name = "rustnish"
version = "0.0.1"
authors = [ "Klaus Purer <klaus.purer@gmail.com>" ]
edition = "2018"

[dependencies]
http = "*"
hyper = ">=0.12"
futures = ">=0.1.14"
error-chain = ">=0.11.0"
tokio = ">=0.1.7"
regex = ">=1"

[dev-dependencies]
tokio-core = ">=0.1.8"
rand = ">=0.4.1"
