[package]
name = "rustnish"
version = "0.0.1"
authors = [ "Klaus Purer <klaus.purer@gmail.com>" ]

[dependencies]
hyper = ">=0.12"
futures = ">=0.1.14"
error-chain = ">=0.11.0"
tokio = ">=0.1.7"

[dev-dependencies]
tokio-core = ">=0.1.8"
